greeting:
  message: "hello"

quarkus:
  infinispan-embedded:
    xml-config: infinispan-tcp-unencrypted.xml
  native:
    resources:
      includes: ["**/*"]
        # - *
        # - META-INF/**
  http:
    port : -1 #  Quarkus의 HTTP 서버 비활성화 (export QUARKUS_HTTP_PORT=8082)
  datasource:
    db-kind: sqlite
    jdbc:
      url: jdbc:sqlite:./mydatabase.db
    devservices:
      enabled: false # Dev Services 비활성화
  log:
    level: INFO
    category:
      "io.route":
        level: DEBUG
    #   "org.infinispan": # Infinispan 로깅 레벨 상세 설정
    #     level: TRACE
    #   "org.jgroups": # JGroups 로깅 레벨 상세 설정
    #     level: TRACE
  blockchain:
    rpc-url: "https://go.getblock.io/82cb819aa8b14b9abd1d0c76e0ab1c68"
    contract-address: "0x0733618ab62eeec815f2d1739b7a50bf9e74d8a2"
    contract-abi-path: "src/main/resources/META-INF/resources/web3/deployed/EcosystemToken.PMG.json"
  # http:
  #   port: 8081