greeting:
  message: "hello"

quarkus:
  infinispan-embedded:
    xml-config: infinispan-tcp-unencrypted.xml
  datasource:
    db-kind: sqlite
    jdbc:
      url: jdbc:sqlite:./mydatabase.db
  # http:
  #   port: 8081